# Generated by Django 4.1.4 on 2023-05-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('nome', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=550)),
                ('imagem', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('git', models.CharField(max_length=250)),
                ('tecnologias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnologia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
            bases=('core.base',),
        ),
    ]
