# Generated by Django 4.1.4 on 2023-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='../static/img/projeto'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icon',
            field=models.ImageField(upload_to='../static/img/icon'),
        ),
    ]
