# Generated by Django 4.1.4 on 2023-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='filtro',
        ),
        migrations.AddField(
            model_name='projeto',
            name='filtro',
            field=models.ManyToManyField(to='core.filtros'),
        ),
    ]
