# Generated by Django 4.1.4 on 2023-05-25 17:42

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projeto_imagem_alter_tecnologia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icon',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={}, verbose_name='icon'),
        ),
    ]
